export const Users = [
  {
    id: 1,
    first_name: "Emiline",
    last_name: "McClune",
    email: "emcclune0@xrea.com",
    gender: "Female",
  },
  {
    id: 2,
    first_name: "Felix",
    last_name: "Ingleston",
    email: "fingleston1@hibu.com",
    gender: "Female",
  },
  {
    id: 3,
    first_name: "Travus",
    last_name: "Bergstram",
    email: "tbergstram2@pbs.org",
    gender: "Female",
  },
  {
    id: 4,
    first_name: "Holly-anne",
    last_name: "Knighton",
    email: "hknighton3@booking.com",
    gender: "Female",
  },
  {
    id: 5,
    first_name: "Sollie",
    last_name: "Naulty",
    email: "snaulty4@hud.gov",
    gender: "Male",
  },
  {
    id: 6,
    first_name: "Annie",
    last_name: "Cockayme",
    email: "acockayme5@tuttocitta.it",
    gender: "Male",
  },
  {
    id: 7,
    first_name: "Celinda",
    last_name: "Sharvill",
    email: "csharvill6@narod.ru",
    gender: "Male",
  },
  {
    id: 8,
    first_name: "Lamond",
    last_name: "Ricket",
    email: "lricket7@washington.edu",
    gender: "Male",
  },
  {
    id: 9,
    first_name: "Florida",
    last_name: "Licciardiello",
    email: "flicciardiello8@sina.com.cn",
    gender: "Female",
  },
  {
    id: 10,
    first_name: "Gerianne",
    last_name: "Jonas",
    email: "gjonas9@typepad.com",
    gender: "Female",
  },
  {
    id: 11,
    first_name: "Amy",
    last_name: "Tarbath",
    email: "atarbatha@t.co",
    gender: "Male",
  },
  {
    id: 12,
    first_name: "Jerrilyn",
    last_name: "Devil",
    email: "jdevilb@upenn.edu",
    gender: "Male",
  },
  {
    id: 13,
    first_name: "Derrik",
    last_name: "Halvorsen",
    email: "dhalvorsenc@loc.gov",
    gender: "Male",
  },
  {
    id: 14,
    first_name: "Kellia",
    last_name: "Driutti",
    email: "kdriuttid@skyrock.com",
    gender: "Male",
  },
  {
    id: 15,
    first_name: "Denys",
    last_name: "Abrams",
    email: "dabramse@godaddy.com",
    gender: "Male",
  },
  {
    id: 16,
    first_name: "Sophie",
    last_name: "Wadmore",
    email: "swadmoref@taobao.com",
    gender: "Male",
  },
  {
    id: 17,
    first_name: "Ivonne",
    last_name: "Axby",
    email: "iaxbyg@paginegialle.it",
    gender: "Male",
  },
  {
    id: 18,
    first_name: "Andee",
    last_name: "Babcock",
    email: "ababcockh@hubpages.com",
    gender: "Female",
  },
  {
    id: 19,
    first_name: "Shawn",
    last_name: "Baxstair",
    email: "sbaxstairi@artisteer.com",
    gender: "Female",
  },
  {
    id: 20,
    first_name: "Randolph",
    last_name: "Chowne",
    email: "rchownej@nymag.com",
    gender: "Male",
  },
];
